/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv ./cloudflare-env.d.ts` (hash: faf8a0423f869fe736da1a5ac5255eb6)
// Runtime types generated with workerd@1.20251011.0 2025-03-01 global_fetch_strictly_public,nodejs_compat
declare namespace Cloudflare {
  interface Env {
    NEXTJS_ENV: string;
    ASSETS: Fetcher;
    lp_template_db: D1Database;
  }
}
interface CloudflareEnv extends Cloudflare.Env {}
